version: "3"

services:
  app:
    container_name: app
    build:
      context: ../../
      dockerfile: docker/dev/Dockerfile
    command: >
      sh -c "python manage.py migrate &&
            python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
    - ../..:/app
    env_file:
      - .env

